# Generated by Django 5.1.3 on 2024-12-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('personal', 'Personal')], default='business', max_length=20),
        ),
    ]
